### ISSUE TITLE
Combat Loop - Error Handle

### ISSUE THREAD

**Issue by spencermcghin** [spencermcghin/mush_test#138]
It is now Gil's turn.
npc gil = hit spencer
hit sil
Could not find 'sil'.
Target not found.
You have been added to the combat loop for the Tavern - Apotheca's Office
Spencer Eldritch has been added to the combat loop for the Tavern - Apotheca's Office.
They are currently number 1 in the round order.
Traceback (most recent call last):
  File "/home/ubuntu/eldritchmush/mush_test/evennia/evennia/commands/cmdhandler.py", line 631, in _run_command
    ret = cmd.func()
  File "/home/ubuntu/eldritchmush/mush_test/eldritchmush/commands/combat_commands/strike.py", line 43, in func
    loop.resolveCommand()
  File "/home/ubuntu/eldritchmush/mush_test/eldritchmush/world/combat_loop.py", line 150, in resolveCommand
    self.addToLoop(self.target.key)
AttributeError: 'NoneType' object has no attribute 'key'

**Comment by spencermcghin** [comment]
Fixed this.
